name: Build Python App for Windows and macOS

on:
  push:
    branches:
      - test  # 每当推送到main分支时触发构建

jobs:
  build_windows:
    runs-on: windows-latest  # Windows 环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # 可根据需要修改Python版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller streamlit pandas plotly
          pip install pandas
          pip install numpy
          pip install -r requirements.txt
          pip install pyinstaller  # 安装 PyInstaller

      - name: Build Windows executable
        run: |
          pyinstaller --onefile main.py  # 替换为你自己的脚本名

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/main.exe  # 生成的Windows可执行文件路径

  build_mac:
    runs-on: macos-latest  # macOS 环境
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller  # 安装 PyInstaller

      - name: Build macOS executable
        run: |
          pyinstaller --onefile main.py  

      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: dist/main  # 生成的macOS可执行文件路径